### ISSUE TITLE
exploring: InvalidReplicationFactorException & SSLHandshakeException

### ISSUE THREAD

**Issue by dfornika** [confluentinc/training-fundamentals-src#22]
When running the 'exploring' lab, I'm getting `InvalidReplicationFactorException` errors complaining that the replication factor is larger than the number of available brokers:

```
exploring-kafka-1      | INFO [Admin Manager on Broker 101]: Error processing create topic request CreatableTopic(name='_confluent-telemetry-metrics', numPartitions=12, replicationFactor=3, assignments=[], configs=[CreateableTopicConfig(name='max.message.bytes', value='10485760'), CreateableTopicConfig(name='message.timestamp.type', value='CreateTime'), CreateableTopicConfig(name='min.insync.replicas', value='1'), CreateableTopicConfig(name='retention.ms', value='259200000'), CreateableTopicConfig(name='segment.ms', value='14400000'), CreateableTopicConfig(name='retention.bytes', value='-1')], linkName=null, mirrorTopic=null) (kafka.server.ZkAdminManager)
exploring-kafka-1      | org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```

I am able to create the `vehicle-positions` topic:

```
$ docker exec exploring-kafka-1 kafka-topics --bootstrap-server kafka:9092 --topic vehicle-positions --create --partitions 6 --replication-factor 1
Created topic vehicle-positions.
$ docker exec exploring-kafka-1 kafka-topics --bootstrap-server kafka:9092 --list
_confluent-metrics
vehicle-positions
```

...but when I attempt to run the producer container, it isn't able to connect:

```
$ docker container run --name producer --net exploring_confluent cnfltraining/vp-producer:v2
*** Starting VP Producer ***
Exception in thread "main" MqttException (0) - javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1321)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
        ... 6 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 10 more
```

I'm not certain that this is related, but when I try to run the producer container, it isn't able to connect,

**Comment by FranciscoOssian** [comment]
same problem, in **2026**
